services:
  sportai:
    build: .
    container_name: sportai
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./scraper:/app/scraper
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
